---

- name: 0. Update cache
  apt:
   update-cache: yes
  changed_when: 0

- name: 1. Install Apache
  apt: name=apache2 state=present

- name: 2. Installing required php modules
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - php
    - libapache2-mod-php
    - git
    - mcrypt
    - php-cli
    - php-curl
    - php-fpm
    - php-intl
    - php-json
    - php-mcrypt
    - mailutils
    - postfix
    - zip
    - unzip
    - curl
    - php-gd
    - php-simplexml
    - php-xml
    - php-date
    - php-imap
    - php-mbstring
    - php-gettext
    - php-zip

- name: 3. Enable mod_rewrite
  apache2_module: name=rewrite state=present

# - name: 3b. enabled dav
#   apache2_module: name=dav state=present
#
# - name: 3c. enabled dav_svn
#   apache2_module: name=dav_svn state=present

- name: 4. Copy Apache vhost
  copy:
    src: files/000-default.conf
    dest: /etc/apache2/sites-available/
    owner: root
    group: root
    force: yes

- name: 5. Restart Apache
  service: name=apache2 state=restarted enabled=yes

# - name: 6. enable php7 mcrypt module
#   shell: php7enmod mcrypt
#   args:
#     creates: /etc/php/7.0/cli/conf.d/20-mcrypt.ini
